--USE master
--ALTER DATABASE EduManagement set single_user WITH ROLLBACK IMMEDIATE
--DROP DATABASE EduManagement
 
CREATE DATABASE EduManagement
 GO
USE EduManagement
 GO

CREATE TABLE Student
(
	StudentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StudentName NVARCHAR(255) NOT NULL,
	StudentPhone NVARCHAR(20) NOT NULL,
	StudentDOB NVARCHAR(15),
	StudentGender NVARCHAR(6),
)
GO

CREATE TABLE Teacher
(
	TeacherId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TeacherName NVARCHAR(255) NOT NULL,
	TeacherPhone NVARCHAR(20) NOT NULL,
	TeacherGender NVARCHAR(6),
	TeacherDOB NVARCHAR(15),
	TeacherEmail NVARCHAR(255),
)
GO

CREATE TABLE Class
(
	ClassId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ClassName NVARCHAR(255),
	ClassYear NVARCHAR(15),
	ClassStatus INT DEFAULT 1,

	TeacherId UNIQUEIDENTIFIER REFERENCES Teacher(TeacherId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE ClassDetail
(
	ClassDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StudentId UNIQUEIDENTIFIER NOT NULL,
	
	ClassId UNIQUEIDENTIFIER REFERENCES Class(ClassId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE SystemUser
(
	SystemUserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserUsername NVARCHAR(255) UNIQUE NOT NULL,
	UserPassword NVARCHAR(255) NOT NULL,
	Fullname NVARCHAR(255) NOT NULL,
	UserPhone NVARCHAR(255) NOT NULL,
	UserDOB NVARCHAR(255),
	UserGender NVARCHAR(255),
)
GO

CREATE TABLE SystemRole
(
	RoleId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	RoleName NVARCHAR(255),
)
GO

CREATE TABLE UserDetail
(
	UserDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER, -- teacherid or null

	SystemUserId UNIQUEIDENTIFIER NOT NULL,
	SystemRoleId INT NOT NULL,
)
GO

CREATE TABLE HomeWork
(
	HomeWorkId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	HomeWorkName NVARCHAR(255) NOT NULL,
	HomeWorkType NVARCHAR(255) NOT NULL,
	HomeWorkContent NVARCHAR(MAX),
	DueDate DATETIME,
	HomeWorkStatus INT DEFAULT 1,
	RequiredLogin BIT DEFAULT 0,
	OnlyAssignStudent BIT DEFAULT 0,
	CreatedDate DATETIME DEFAULT GETDATE(),

	TeacherId UNIQUEIDENTIFIER,
)
GO

CREATE TABLE HomeWorkClassDetail
(
	HomeWorkClassDetail  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId),
	ClassId UNIQUEIDENTIFIER REFERENCES Class(ClassId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE FileUpload
(
	FileUploadId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadUrl NVARCHAR(255) NOT NULL,
	FileUploadName NVARCHAR(255) NOT NULL,
)
GO

CREATE TABLE HomeWorkFileDetail
(
	FileUploadDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadId UNIQUEIDENTIFIER REFERENCES FileUpload(FileUploadId),
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE Answer
(
	AnswerId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	SubmitTime DATETIME NOT NULL,
	AnswerContent NVARCHAR(MAX),
	CreatedDate DATETIME DEFAULT GETDATE(),
	ModifyDate DATETIME DEFAULT GETDATE(),
	
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId),
	StudentId UNIQUEIDENTIFIER REFERENCES Student(StudentId),
	ClassId UNIQUEIDENTIFIER,
)
GO

CREATE TABLE AnswerFileDetail
(
	FileUploadDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadId UNIQUEIDENTIFIER REFERENCES FileUpload(FileUploadId),
	AnswerId UNIQUEIDENTIFIER REFERENCES Answer(AnswerId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE Result
(
	ResultId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FinalScore NVARCHAR(4) DEFAULT N'0.0',
	ResultContent NVARCHAR(MAX),
	CreatedDate DATETIME DEFAULT GETDATE(),
	ModifyDate DATETIME DEFAULT GETDATE(),
	
	TeacherId UNIQUEIDENTIFIER REFERENCES Teacher(TeacherId),
	AnswerId UNIQUEIDENTIFIER REFERENCES Answer(AnswerId),
)
GO

INSERT INTO SystemRole
VALUES
	(N'admin'),
	(N'teacher'),
	(N'student')
GO

INSERT INTO SystemUser
VALUES
	(N'DD114F18-0493-4E35-9BBC-663B8C5E6C61', 
N'0979045160',
N'e10adc3949ba59abbe56e057f20f883e', 
N'Hoang Nguyen', 
N'0979045160',
N'23/07/1999',
N'Nam'
), (N'8A1B746B-C6F9-4627-B803-271ADB35C289', 
N'hoag-admin', 
N'21232f297a57a5a743894a0e4a801fc3', 
N'Admin', 
N'1',
null,
null
), (N'F54565DB-D95B-470B-BFA2-A8CAF34EE632', 
N'0979045161', 
N'e10adc3949ba59abbe56e057f20f883e', 
N'Nguyễn Hoàng', 
N'0979045161',
N'23/07/1999',
N'Nam'
)
 GO

INSERT INTO Student 
Values (N'10F917AB-A3D8-4AF5-B350-BE29B5F76432', N'Nguyễn Hoàng', '0979045161', N'23/07/1999', N'Nam')
INSERT INTO Teacher
VALUES
	(N'88CA6417-6B71-48B2-9FD9-47C57F384947', 
	N'Hoang',
	N'0979045160',
	N'Nam',
	N'23/07/1999',
	NULL)
 GO

 INSERT INTO UserDetail
 VALUES
 	(DEFAULT, NULL, N'8A1B746B-C6F9-4627-B803-271ADB35C289', 1),
 	(DEFAULT, N'88CA6417-6B71-48B2-9FD9-47C57F384947', N'DD114F18-0493-4E35-9BBC-663B8C5E6C61', 2),
 	(DEFAULT, null, N'F54565DB-D95B-470B-BFA2-A8CAF34EE632', 3)
 GO

INSERT INTO Class
VALUES
	(N'72E24AAA-F3EF-49B5-8C2E-2C869B688C42', N'1A1', N'2022-2023', 1, N'88CA6417-6B71-48B2-9FD9-47C57F384947'),
	(N'03F47CCC-24B4-484F-B08F-370B3DCBE2BA', N'1A2', N'2022-2023', 1, N'88CA6417-6B71-48B2-9FD9-47C57F384947')
GO

SELECT UserDetail.* FROM UserDetail, SystemUser
WHERE SystemUser.SystemUserId = UserDetail.SystemUserId
AND SystemUser.UserPhone = N'0979045161'
AND UserDetail.SystemRoleId = 3

SELECT Student.* FROM Class, ClassDetail, Student
WHERE Class.ClassId = N'7a5f83a4-7dd3-489c-a992-cfb7a0e61c32'
AND ClassDetail.ClassId = Class.ClassId
AND ClassDetail.StudentId = Student.StudentId

select * from Class, ClassDetail
WHERE Class.ClassId = N'7a5f83a4-7dd3-489c-a992-cfb7a0e61c32'
AND Class.ClassId = ClassDetail.ClassId

SELECT DISTINCT Class.*, (
	SELECT DISTINCT count(*) 
	FROM HomeWorkClassDetail, HomeWork
	WHERE HomeWorkClassDetail.ClassId = Class.ClassId
	AND HomeWork.HomeWorkId = HomeWorkClassDetail.HomeWorkId
	AND HomeWork.HomeWorkStatus = 1
) as HomeWorkCount 
FROM Class
WHERE Class.TeacherId =  N'88ca6417-6b71-48b2-9fd9-47c57f384947'
AND Class.ClassStatus = 1

select * from Class
where Class.TeacherId = N'88ca6417-6b71-48b2-9fd9-47c57f384947'

SELECT DISTINCT Class.*, (
	SELECT DISTINCT count(*) 
	FROM HomeWorkClassDetail, HomeWork
	WHERE HomeWorkClassDetail.ClassId = Class.ClassId
	AND HomeWork.HomeWorkId = HomeWorkClassDetail.HomeWorkId
	AND HomeWork.HomeWorkStatus = 1
) as HomeWorkCount 
FROM Class, ClassDetail
WHERE ClassDetail.StudentId = N'10f917ab-a3d8-4af5-b350-be29b5f76432'
AND ClassDetail.ClassId = Class.ClassId
AND Class.ClassStatus = 1

select * from SystemUser