--USE master
--ALTER DATABASE EduManagement set single_user WITH ROLLBACK IMMEDIATE
--DROP DATABASE EduManagement

CREATE DATABASE EduManagement
 GO
USE EduManagement
 GO

CREATE TABLE Student
(
	StudentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StudentName NVARCHAR(255) NOT NULL,
	StudentPhone NVARCHAR(20) NOT NULL,
	StudentGender NVARCHAR(6),
)
GO

CREATE TABLE Teacher
(
	TeacherId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TeacherName NVARCHAR(255) NOT NULL,
	TeacherPhone NVARCHAR(20) NOT NULL,
	TeacherGender NVARCHAR(6),
	TeacherDOB NVARCHAR(15),
	TeacherEmail NVARCHAR(255),
)
GO

CREATE TABLE Class
(
	ClassId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ClassName NVARCHAR(255),
	ClassYear NVARCHAR(15),
	ClassStatus INT,

	TeacherId UNIQUEIDENTIFIER REFERENCES Teacher(TeacherId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE ClassDetail
(
	ClassDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StudentId UNIQUEIDENTIFIER NOT NULL,
	
	ClassId UNIQUEIDENTIFIER REFERENCES Class(ClassId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE SystemUser
(
	SystemUserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Username NVARCHAR(255) NOT NULL,
	UserUsername NVARCHAR(255) UNIQUE NOT NULL,
	UserPassword NVARCHAR(255) NOT NULL,
)
GO

CREATE TABLE SystemRole
(
	RoleId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	RoleName NVARCHAR(255),
)
GO

CREATE TABLE UserDetail
(
	UserDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER,
	-- can be teacherid, studentid or null

	SystemUserId UNIQUEIDENTIFIER NOT NULL,
	SystemRoleId INT NOT NULL,
)
GO

CREATE TABLE HomeWork
(
	HomeWorkId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	HomeWorkName NVARCHAR(255) NOT NULL,
	HomeWorkType NVARCHAR(255) NOT NULL,
	HomeWorkDescribe NVARCHAR(MAX),
	DueDate DATETIME,
	HomeWorkStatus INT,
	RequiredLogin BIT DEFAULT 0,
	OnlyAssignStudent BIT DEFAULT 0,
	CreatedDate DATETIME DEFAULT GETDATE(),

	TeacherId UNIQUEIDENTIFIER,
)
GO

CREATE TABLE HomeWorkClassDetail
(
	HomeWorkClassDetail  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId) ON DELETE CASCADE NOT NULL,
	ClassId UNIQUEIDENTIFIER REFERENCES Class(ClassId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE FileUpload
(
	FileUploadId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadUrl NVARCHAR(255) NOT NULL,
	FileUploadName NVARCHAR(255) NOT NULL,
)
GO

CREATE TABLE HomeWorkFileDetail
(
	FileUploadDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadId UNIQUEIDENTIFIER REFERENCES FileUpload(FileUploadId) ON DELETE CASCADE NOT NULL,
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE Answer
(
	AnswerId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	AnswerName NVARCHAR(255) NOT NULL,
	StartTime DATETIME NOT NULL,
	FinishTime DATETIME,
	FinishDuration NVARCHAR(255),
	
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId) ON DELETE CASCADE NOT NULL,
	StudentId UNIQUEIDENTIFIER REFERENCES Student(StudentId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE AnswerFileDetail
(
	FileUploadDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FileUploadId UNIQUEIDENTIFIER REFERENCES FileUpload(FileUploadId) ON DELETE CASCADE NOT NULL,
	AnswerId UNIQUEIDENTIFIER REFERENCES Answer(AnswerId) ON DELETE CASCADE NOT NULL,
)
GO

CREATE TABLE Result
(
	ResultId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FinalScore NVARCHAR(4) DEFAULT N'0.0',
	CreatedDate DATETIME DEFAULT GETDATE(),

	TeacherId UNIQUEIDENTIFIER,
)
GO

CREATE TABLE HomeWorkResultDetail
(
	HomeWorkResultDetailId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ResultId UNIQUEIDENTIFIER REFERENCES Result(ResultId) ON DELETE CASCADE NOT NULL,
	AnswerId UNIQUEIDENTIFIER REFERENCES Answer(AnswerId),
	HomeWorkId UNIQUEIDENTIFIER REFERENCES HomeWork(HomeWorkId),
)
GO


INSERT INTO SystemRole
VALUES
	(N'admin'),
	(N'teacher'),
	(N'student')
GO
INSERT INTO SystemUser
VALUES
	(N'DD114F18-0493-4E35-9BBC-663B8C5E6C61', N'Teacher Test', N'0979045160', N'e10adc3949ba59abbe56e057f20f883e'), 
	(N'8A1B746B-C6F9-4627-B803-271ADB35C289', N'Admin', N'hoag-admin', N'21232f297a57a5a743894a0e4a801fc3'),
	(N'A2E48929-2688-4F4F-8EE2-291D67568888', N'Teacher Hoag', N'09123123123', N'e10adc3949ba59abbe56e057f20f883e')
 GO

INSERT INTO Teacher
VALUES
	(N'88CA6417-6B71-48B2-9FD9-47C57F384947', 
	N'Hoang',
	N'0979045160',
	N'Nam',
	N'23/07/1999',
	NULL),
	(N'D60C8577-585E-44CC-8AD0-70B052875FA8', 
	N'Teacher Hoag',
	N'09123123123',
	N'Nam',
	N'23/07/1999',
	NULL)
 GO

 INSERT INTO UserDetail
 VALUES
 	(DEFAULT, NULL, N'8A1B746B-C6F9-4627-B803-271ADB35C289', 1),
 	(DEFAULT, N'88CA6417-6B71-48B2-9FD9-47C57F384947', N'DD114F18-0493-4E35-9BBC-663B8C5E6C61', 2),
 	(DEFAULT, N'D60C8577-585E-44CC-8AD0-70B052875FA8', N'A2E48929-2688-4F4F-8EE2-291D67568888', 2)
 GO

INSERT INTO Class
VALUES
	(N'72E24AAA-F3EF-49B5-8C2E-2C869B688C42', N'1A1', N'2022-2023', 1, N'88CA6417-6B71-48B2-9FD9-47C57F384947'),
	(N'03F47CCC-24B4-484F-B08F-370B3DCBE2BA', N'1A2', N'2022-2023', 1, N'88CA6417-6B71-48B2-9FD9-47C57F384947')
GO

select * from Class

